language: ruby

rvm:
  - 2.3.3

sudo: false

before_install: gem install bundler -v 1.16.0

gemfile:
  - gemfiles/activerecord_4_2.gemfile
  - gemfiles/activerecord_5_0.gemfile
  - gemfiles/activerecord_5_1.gemfile
  - gemfiles/activerecord_5_2.gemfile